### ISSUE TITLE
Using with Guzzle 6.0

### ISSUE THREAD

**Issue by ssssteve** [joetannenbaum/phpushbullet#6]
Hi,

I'm trying to use lahaxearnaud/laravel-pushbullet, which uses this project, but installation with Composer chokes on the requirement here for guzzlehttp/guzzle ~5.0. 

GuzzleHttp is now at 6 (actually 6.1.1) - is there any reason why this package would not work with ~6.0?

**Comment by joetannenbaum** [comment]
There's not a specific reason, no. Would just require a minor re-working of some of the tests and Client setup. I can look at this in the next day or two and push it up.

**Comment by ssssteve** [comment]
OK, sounds great to me!

**Comment by lahaxearnaud** [comment]
I will check to update laravel-pushbullet depencies when you will make the change =)

**Comment by ssssteve** [comment]
Excellent! Thanks both for your work.

**Comment by ssssteve** [comment]
Hi @joetannenbaum, any update on this?

**Comment by joetannenbaum** [comment]
Hey @ssssteve, I think we're good here. It's in master now, I'll tag it up in just a bit to make it official.

Sorry for the delay, my 9-5 ramped up and I got sidetracked there for a bit.

**Comment by joetannenbaum** [comment]
All set here, tagged as 1.2.1. Thanks for your patience.

**Comment by ssssteve** [comment]
OK, thanks v. much for your help
