### ISSUE TITLE
Fatal error: Class 'PHPushbullet\PHPushbullet' not found in

### ISSUE THREAD

**Issue by stormcaster** [joetannenbaum/phpushbullet#7]
Hi! I need some help with integration...

"Fatal error: Class 'PHPushbullet\PHPushbullet' not found in... "

$pushbullet = new PHPushbullet\PHPushbullet('my_access_token');

Whats wrong?

**Comment by stormcaster** [comment]
if i remove this, i get "Call to a member function device() on a non-object in ..."

**Comment by joetannenbaum** [comment]
Are you including the vendor autoload file before instantiating the class?

```php
require_once('vendor/autoload.php');

$pushbullet = new PHPushbullet\PHPushbullet('my_access_token');
```

**Comment by lahaxearnaud** [comment]
If you required the autoloader and you still have the error please double check your namespace.

If you are in a namespace you can try 

```php
$pushbullet = new \PHPushbullet\PHPushbullet('my_access_token');
```

or before you class declaration :

```php
use PHPushbullet\PHPushbullet;

class MyAwesomClass
{ ... }
```

then

```php
$pushbullet = new PHPushbullet('my_access_token');
```

**Comment by joetannenbaum** [comment]
Closing this, re-open if the problem persists.
