### ISSUE TITLE
Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, boolean given, called in vendor\guzzlehttp\guzzle\src\Client.php on line 87 and defined

### ISSUE THREAD

**Issue by Advil-Robin** [joetannenbaum/phpushbullet#9]
Yep, that error is what I get here.

I'm using this plugin and another one: [https://github.com/lahaxearnaud/laravel-pushbullet](https://github.com/lahaxearnaud/laravel-pushbullet)

The only problem is, I always get this error:

```
ErrorException in Client.php line 126:
Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, boolean given, called in \vendor\guzzlehttp\guzzle\src\Client.php on line 87 and defined
```

Anyone who can fix this for me?

I installed all the plugins using the lahaxearnaud installation thing.

**Comment by joetannenbaum** [comment]
Can you give me a sample of the code you are trying to run when you get the error?

**Comment by Advil-Robin** [comment]
I use this code in a controller"

`PushBullet::all()->note('Belangrijk', 'Er is een nieuw contact bericht.');` wich does the request. When that is fired, I got the error.

**Comment by joetannenbaum** [comment]
Ok, I just merged the pull request from @lahaxearnaud and tagged PHPushbullet 1.2.2 which should fix this problem.

**Comment by RosiersRobin** [comment]
Updated everything, still get the same error.

**Comment by joetannenbaum** [comment]
lahaxearnaud/laravel-pushbullet still has to tag the new version, the changes to make it work are still in the master branch. Once it's tagged you can update and everything should be good.

**Comment by RosiersRobin** [comment]
Ah Didn't know, Okay, thanks!
